### PR TITLE
validate-ads

### PR DESCRIPTION
**Pull request by rorrell**
…ient side validation to her form for new ads (since we wouldn't want to reload the page)

### CODE REVIEW

**Comment by rorrell** [comment]
@muse-gabs please take a look when you can

**Comment by rorrell** [comment]
@muse-gabs , I merged in @natetonal 's latest dashboard branch and updated my changed to work with those changes to the form.  Please review and merge soon so I don't have to keep chasing after new changes.

**Comment by rorrell** [comment]
Hey @muse-gabs , did you ever get back to this?

**Comment by muse-gabs** [comment]
I think Nate already added it to his branch, can check with him

**Comment by monetholt** [comment]
I just brought this up to date with master and Gabrielle is right that Nate already incorporated these changes so they were in master already. I merged anyway because there was one deletion in app.js of an unused function that I figured was worth updating in master: https://github.com/monetholt/quaver-n-bits/pull/11/files

**Pull request merged**
